// AICL dashboard — DEMO DATA adapter (developer mode only).
// Loaded via dynamic import() only when the operator explicitly enables demo mode
// (?demo=1 or the login dialog button). It is never used as a fallback after API errors.
// Data: deterministic fixtures generated by tests/dashboard/generate_demo_fixtures.py.
// Timestamps are shifted so the fixture anchor maps to "now" (relative times stay meaningful).

import { ApiError } from '../api.js';
import { parseJsonl } from '../normalize.js';

const TS_KEYS = new Set(['ts', 'generated_at', 'loaded_at', 'resets_at', 'window_started_at', 'from', 'to', 'since', 'last_run']);

function rebase(obj, deltaMs) {
  if (Array.isArray(obj)) return obj.map((x) => rebase(x, deltaMs));
  if (obj && typeof obj === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(obj)) {
      if (TS_KEYS.has(k) && typeof v === 'string' && v.endsWith('Z')) {
        const t = Date.parse(v);
        out[k] = Number.isNaN(t) ? v : new Date(t + deltaMs).toISOString();
      } else out[k] = rebase(v, deltaMs);
    }
    return out;
  }
  return obj;
}

export function createDemoAdapter({ base = './demo/' } = {}) {
  let loaded = null;
  let delta = 0;

  async function getJson(name) {
    const res = await fetch(base + name, { cache: 'no-store' });
    if (!res.ok) throw new ApiError(res.status === 404 ? 'not_found' : 'server', `Demo fixture ${name} missing [HTTP ${res.status}]`, { status: res.status, endpoint: name });
    return res.json();
  }

  function load() {
    if (!loaded) {
      loaded = (async () => {
        const manifest = await getJson('manifest.json');
        delta = Date.now() - Date.parse(manifest.anchor);
        const res = await fetch(`${base}audit.sample.jsonl`, { cache: 'no-store' });
        if (!res.ok) throw new ApiError('server', 'Demo audit fixture missing', { status: res.status });
        const { events } = parseJsonl(await res.text());
        const names = ['healthz', 'summary', 'latency', 'budgets', 'controls', 'policy', 'test_report', 'fuzz_report'];
        const payloads = Object.fromEntries(await Promise.all(names.map(async (n) => [n, await getJson(`${n}.json`)])));
        return { manifest, events, payloads };
      })();
      loaded.catch(() => { loaded = null; });
    }
    return loaded;
  }

  const get = (name) => async () => rebase((await load()).payloads[name], delta);

  return {
    demo: true,
    isInflight: () => false,
    abort() {},
    abortAll() {},
    health: get('healthz'),
    summary: get('summary'),
    latency: get('latency'),
    budgets: get('budgets'),
    controls: get('controls'),
    policy: get('policy'),
    async events({ limit = 2000, since, action, control, identity } = {}) {
      const { events } = await load();
      const sinceMs = since ? Date.parse(since) : -Infinity;
      const now = Date.now();
      const out = [];
      for (let i = events.length - 1; i >= 0 && out.length < limit; i--) {
        const e = rebase(events[i], delta);
        const t = Date.parse(e.ts);
        if (t > now || t < sinceMs) continue;
        if (action && e.final_action !== action) continue;
        if (identity && e.identity !== identity) continue;
        if (control && !(e.decisions || []).some((d) => d.control_id === control)) continue;
        out.push(e);
      }
      return { events: out, demo: true };
    },
    async report(key) {
      const name = key === 'tests' ? 'test_report' : key === 'fuzz' ? 'fuzz_report' : null;
      if (!name) throw new ApiError('not_found', 'Unknown demo report');
      return rebase((await load()).payloads[name], delta);
    },
    async validatePolicy() {
      throw new ApiError('not_found', 'Policy validation needs a running gateway — not available with DEMO DATA.', { status: 404 });
    },
    async reloadPolicy() {
      throw new ApiError('not_found', 'Policy reload needs a running gateway — not available with DEMO DATA.', { status: 404 });
    },
    async exportAudit() {
      const { events } = await load();
      const now = Date.now();
      const lines = events.map((e) => rebase(e, delta)).filter((e) => Date.parse(e.ts) <= now).map((e) => JSON.stringify(e));
      return { blob: new Blob([`${lines.join('\n')}\n`], { type: 'application/x-ndjson' }) };
    },
    async chat({ model, prompt, identity } = {}) {
      const isInj = /ignore|override|zignoruj/i.test(prompt);
      if (isInj) {
        const err = new ApiError('forbidden', 'Request blocked by demo security layer (C-INJ-PAT)', { status: 403, details: { error: { type: 'aicl_blocked', message: 'blocked by C-INJ-PAT: matched pattern', control_id: 'C-INJ-PAT', threat_ids: ['TH-01'] } } });
        err.action = 'block';
        err.overheadMs = '0.45';
        err.requestId = 'req_demo_' + Math.random().toString(36).slice(2, 8);
        throw err;
      }
      return {
        status: 200,
        action: 'allow',
        overheadMs: '0.35',
        requestId: 'req_demo_' + Math.random().toString(36).slice(2, 8),
        data: { choices: [{ message: { content: `[DEMO RESPONSE] Answered by ${model || 'mock-commercial'} for ${identity || 'support-agent-01'}.` } }] },
      };
    },
  };
}
