"""Regenerate policies/hybrid.yaml from policies/default.yaml (keeps the two in sync).

    python scripts/make_hybrid_policy.py

hybrid.yaml = default.yaml with the AI tiers switched on: C-INJ-EMB on Ollama (bge-m3),
C-INJ-BASTION on ProtectAI (ONNX) and the judge on qwen2.5:1.5b, with CPU-sized timeouts.
Edit default.yaml, then run this script; never edit hybrid.yaml by hand.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
HEADER = """\
# GENERATED by scripts/make_hybrid_policy.py from policies/default.yaml - do not edit by hand.
# Hybrid multi-tier defense: the AI tiers are on. Use it with
#   AICL_POLICY=policies/hybrid.yaml  AICL_OLLAMA_URL=http://localhost:11434
#   pip install -e ".[protectai]"; ollama pull bge-m3; ollama pull qwen2.5:1.5b
# (docker compose --profile hybrid up does all of this). Setup: docs/SEMANTIC_SETUP.md
"""

# (text in default.yaml, replacement) - each must occur exactly once
CHANGES = [
    ('meta: {name: default-policy, description: "Sample policy, 3 strictness levels"}',
     'meta: {name: hybrid-policy, description: "Hybrid multi-tier defense (AI tiers on)"}'),
    ("      backend: none                     # none (skipped) | ollama (/api/embed)",
     "      backend: ollama                   # none (skipped) | ollama (/api/embed)"),
    ("      timeout_ms: 3000                  # one batch per request",
     "      timeout_ms: 6000                  # one batch per request"),
    ("      backend: none                     # none (skipped) | protectai",
     "      backend: protectai                # none (skipped) | protectai"),
    ("  timeout_ms: 4500\n", "  timeout_ms: 12000                     # CPU: ~3-8 s per verdict\n"),
]


def build(default_text: str) -> str:
    text = default_text
    for old, new in CHANGES:
        if text.count(old) != 1:
            raise SystemExit(f"default.yaml changed, update CHANGES: {old!r} found {text.count(old)}x")
        text = text.replace(old, new)
    return HEADER + "\n" + text


def main() -> None:
    src = (REPO / "policies" / "default.yaml").read_text(encoding="utf-8")
    (REPO / "policies" / "hybrid.yaml").write_text(build(src), encoding="utf-8")
    print("policies/hybrid.yaml regenerated")


if __name__ == "__main__":
    main()
